name: Pull + rebuild + reboot pm2

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: rebuild
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.PRIVATE_KEY }}