name: Pull + rebuild + reboot pm2

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: rebuild
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd fruitfulapp.com
            git pull
            npm install
            npx tsc
            cd client
            npm run build
            pm2 restart server client
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}